- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithInlineAssignFixture.php
Fixes #13
When a variable is found, we use `findWhereAssignExecuted()` to consider where to mark that variable as "ready to be used" (eg: this is illegal if `$foo` is not defined: `$foo = $foo + 1;`). It checks for semicolons or closing parenthesis and returns whichever comes first.
In this case, the expression `($foo = 1, $foo)` uses the variable before either a semicolon or a parenthesis; instead it uses a comma.
This PR adds `T_COMMA` as a possible ending token as well.
> Fix inline assign and access

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
> Allow `$this` within closures

- VariableAnalysis/Tests/BaseTestCase.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
Errors and warnings (messages) are not always added in line-number order since they can be added by different sniffs or different parts of a sniff in whatever order the sniff chooses. That's fine, but our tests aren't particularly concerned with the order of the messages, just if they exist on the correct lines.
This change sorts all the line numbers being reported for tests so that we can assume they are always in increasing integer order.
> Tests: sort line numbers

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
The current min version for this standard is PHP 5.4 which does not have it.
> Remove null coalesce

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This is just some more clean-up and organization.
> Simplify handling static variables

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithVariableCallFixture.php
> Fix recognition of variable functions

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithForeachFixture.php
This fixes a major bug introduced in #35 in which variables defined in code
after a foreach statement were incorrectly considered to be declared by that
foreach statement.
Fixes #33 again
> Fix broken foreach variable identification

- README.md
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithUnusedParamsFixture.php
There are already three options for ignoring unused variables. This PR adds documentation for those options and also adds a new option to allow ignoring variables by regular expression. This will bring the available options to the following:
- `allowUnusedFunctionParameters` (bool, default `false`): if set to true, function arguments will never be marked as unused.
- `allowUnusedCaughtExceptions` (bool, default `false`): if set to true, caught Exception variables will never be marked as unused.
- `validUnusedVariableNames` (string, default `null`): a space-separated list of names of placeholder variables that you want to ignore from unused variable warnings. For example, to ignore the variables `$junk` and `$unused`, this could be set to `'junk unused'`.
- `ignoreUnusedRegexp` (string, …
> Allow unused function arguments as regexp

- composer.json
Without this, there is no generic way how to reference to sniffs here. This also means it can't be used with EasyCodingStandard
> Add composer autoload configuration

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ClassWithMembersFixture.php
> Include `parent` keyword as static reference

- .circleci/config.yml
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/BaseTestCase.php
I didn't realize that the typehints I was using in this sniff were not a feature added until PHP 7. Since this sniff supports PHP 5.4, I had to remove them.
Fixes #46
> Remove typehints to support PHP 5

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithUseReferenceFixture.php
Pass-by-reference variables are currently correctly [marked as such](https://github.com/sirbrillig/phpcs-variable-analysis/blob/d7652aff800e43cc54ccdcc0d4e2956a10ba7a07/VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php#L251-L255) in function parameters, but not in anonymous functions' `use` constructs.
This PR marks according pass-by-reference variables correctly and thus fixes #51.
> Correctly mark pass-by-reference variables in use() constructs

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/DestructuringFixture.php
This adds support for shorthand list assignment, also known as shorthand array destructuring assignment.
That is, this will now count as assignment of both `$a` and `$b`.
```php
[$a, $b] = [1, 2];
```
Fixes #48
> Support shorthand list assignment

- README.md
- VariableAnalysis/Lib/VariableInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ClassReferenceFixture.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithGlobalVarFixture.php
I made an issue an issue about this #55 before realizing it wasn't an option, so I thought I'd implement it and submit the feature request.
This feature should be used with caution, but for certain settings, notably the WordPress $post global variable, it is nice to avoid the repetition of writing `global $post` on all WordPress theme included files in the loop. This helps reduce noise when reviewing WordPress themes, while not having to disable variable analysis completely.
I also added some tests for this in the global space.
> Option for undefined vars

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Lib/ScopeInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/UnusedAfterUsedFixture.php
- composer.json
- phpcs.xml.dist
This adds a new option, `allowUnusedParametersBeforeUsed`, which will allow unused function arguments if they come before a used argument.
Fixes #57
> Add allowUnusedParametersBeforeUsed option

- README.md
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/UnusedAfterUsedFixture.php
#58 added a new option `allowUnusedParametersBeforeUsed`, which, if set, ignores unused function arguments if they come before used function arguments. Since it's probably rare that those warnings would be needed, this PR changes that option to default to `true`.
> Make allowUnusedParametersBeforeUsed default to true

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/PregReplaceFixture.php
Variable names which start with a number are illegal in PHP, but the pattern of a `$` followed by a number inside a string is used by some constructs such as `preg_replace()`. This change simply does not process symbols that look like variables if the variable name starts with a number.
Fixes #60
> Ignore numeric variables

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ClassWithMembersFixture.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithVariableCallFixture.php
When I was checking for all the different ways to reference static properties and functions, somehow I missed the formation `$variable::$property` (a static property on a dynamic class reference). This corrects that failure.
Fixes #62
> Handle variable class static refs

- .gitignore
- README.md
- VariableAnalysis/Lib/VariableInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/UnusedForeachFixture.php
This adds a new option, `allowUnusedForeachVariables`. If the option is set to true, it will cause unused keys or values created by the `as` statement in a `foreach` loop to never be marked as unused.
With this option unset, the following block would produce two warnings. Neither `$key` nor `$value` are used. With the option set, neither of these warnings will be recorded.
```php
foreach ($array as $key => $value) {
echo 'hello';
}
```
Fixes #65
> Add ignore unused foreach option

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithClosureFixture.php
Since this sniff has a minimum version of PHP 5.4 and in that version PHP will autobind `self` inside class method closures, this disables errors for those cases.
Fixes #68
> Allow self within class method closures

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/AnonymousClassFixture.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/AnonymousClassWithPropertiesFixture.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ClassWithMembersFixture.php
Prior to now, the sniff was treating class property declarations as regular variable declarations in some cases and property reads in other cases. I think this was causing some odd bugs, like #75.
This PR adds an explicit check for class property declarations (using `public`, `private`, `protected`, `var`, `static`, or `public static`, etc.) and ignores them.
Fixes #75
> Add checks for class properties

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/TraitWithMembersFixture.php
Maybe I'm missing something since I can hardly believe I'm the first one to encounter this issue. But it seems `self::` and `static::` are not allowed in traits.
This pr fixes that
> allow self and static references in trait

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ClassWithMembersFixture.php
When trying to determine if a static keyword is being used to define a static
class property or a static variable, we were checking only to see if the
enclosing block was a function. However, if the enclosing block is (for
example) an if statement inside a function, then this check would fail when it
should pass.
This change instead checks for any enclosing function, so long as the enclosing
function comes before the enclosing class (to prevent false positives when a
function returns an anonymous class).
Fixes #79
> Improve check for static var defs inside functions

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Lib/VariableInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithGlobalVarFixture.php
Typically when a variable is assigned a value within a scope, and then never used for any other purpose, it triggers an unused variable warning in this sniff. However, when the `global` keyword is used to import a variable into the scope, an assignment is a side-effect and therefore should count as using the variable (this is the same as the behavior of [pass-by-reference](5e094b727dced730142e8ecf30200506223df7ef)). This PR fixes `processScopeCloseForVariable()` to support that behavior.
Fixes #81
> Allow global var assignment to count as a read

- .circleci/config.yml
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/BaseTestCase.php
- composer.circleci.json
- composer.json
- phpunit.circleci.xml
To ensure that the code still works for old versions of PHP.
Fixes #85
> Downgrade circleci image to PHP 5.6

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/VariableVariablesFixture.php
When a variable variable is used as the left side of an assignment, there are actually two variables being checked: there is the current one, and the variable one whose name is the value of the current one.
In this case, we must not treat the current one as an assignment; it is actually a read. This change updates the logic so that this is the case.
Fixes #84 
This does not address the issue that variable variables are not marked as used (see #87).
> Recognize that variable vars are not assignments

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/GetDefinedVarsFixture.php
When `get_defined_vars()` is called, it should count as a read (a usage) of all the variables in the current scope.
Fixes #91
> Consider `get_defined_vars()` to be a read

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This shouldn't have any functional change, but it refactors a bunch of methods which currently return a value or `false` to return a value or `null`. Since PHP 7.1 supports nullable return types, this pattern has been shown to be more standard than the ... "falsable" 🤔 return type that I had been using to signal failure.
> Refactor methods to have nullable return types

- README.md
- composer.json
PHPCS is a direct dependency for this utility to be run, so should be in `require`.
The problem with not having it there is that other external /project rulesets may have different PHPCS requirements and Composer will not be able to take the requirements for this project into consideration when doing the version negotiations unless the dependency is explicitly set in `require`.
Relying on PHPCS being installed with the DealerDirect plugin is not stable as they may change their minimum required PHPCS version without notice.
As the minimum version in the `composer.json` file and the one in the `README` were not in line (though very close), I've also updated the minimum required version as mentioned in the `README` to be in line.
**Question**: as the Composer install instructions already …
> Composer: move PHPCS dependency to `require`

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/AnonymousClassWithPropertiesFixture.php
The use of `self::$property`/`static::$property` in non-nested anonymous classes was incorrectly flagged as `SelfOutsideClass`/`StaticOutsideClass` (false positive).
For use within anonymous classes nested within another class, the only reason these weren't flagged was the fact that they were nested.
Fixed now.
Includes unit tests.
> Bug fix: recognize use of self/static within anonymous class

- phpunit.circleci.xml
- phpunit.xml.dist
This is a required attribute for PHPUnit 7+ and allowed in older versions.
> PHPUnit config: add testsuite name

- .circleci/config.yml
- composer.json
- phpcs.xml.dist
This makes it easier for contributors to run the PHPCS command for the project.
Includes:
* Adding the `Tests` directory to the run - excluding the test case files in `fixtures`.
* Cleaning up the result report by using the `basepath` configuration.
* Making the run faster by using `parallel` scanning if available,
> PHPCS: document run parameters in project ruleset

- composer.json
The DealerDirect Composer plugin released version 0.5.0 over a year ago. Let's allow using it.
Ref: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.5.0
> Composer: update DealerDirect Composer plugin requirement

- VariableAnalysis/Tests/BaseTestCase.php
I'm not completely sure why, but when I tried to run the unit tests locally, most were failing.
This minor tweak in how PHPCS is instantiated fixes it. It also removes the need for the `getSniffFiles()` method as there is only one sniff in this standard anyway.
> Unit test: fix tests failing

- composer.circleci.json
- composer.json
... and the same across configs. Composer will sort out which version will actually be installed.
> Composer: make the PHPUnit requirements more flexible

- VariableAnalysis/Tests/BaseTestCase.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- Remove the `$sniffFiles` parameter which doesn't change between calls to the method anyway and replace it with a class constant and a call to `realpath()` within the function.
- Remove the `getSniffFiles()` method which is now no longer needed.
- Adjust all calls to the `prepareLocalFileForSniffs()` method to remove the parameter.
[1] = yes, more simplifications upcoming, but doing it step by step to allow for easier reviewing of the changes.
> Tests: simplify the PHPCS setup method [1]

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
Token constants can be integers (native PHP tokens) or strings (PHPCS native tokens and backfilled PHP tokens).
> Documentation: minor fixes

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ThisWithinNestedClosedScopeFixture.php
While `$this` can be used freely within classes, traits and closures, if a nested closed scope is defined within any of these, `$this` is not inherited and should be considered undefined.
As things were, the sniff would not throw a warning for this (false negative).
This commit fixes this.
Includes unit tests.
Includes removing an outdated comment. `T_CLOSURE` works perfectly fine with the conditions array (and has for quite a few years).
Fixes #109
> Bug fix: $this in nested function declaration

- composer.json
- phpstan.neon
- phpstan.neon.dist
This makes it easier to run the PHPStan command for the project.
Includes:
* Using `%currentWorkingDirectory%` instead of `%rootdir%`
* Renaming the file to `phpstan.neon.dist` to allow overloading of the config by individual developers.
> PHPStan: document run parameters in project ruleset

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/UnusedVarWithValueChangeFixture.php
- phpstan.neon.dist
As reported in #111, if a variable is assigned a value with a combined assignment operator, it would not be reported as unused.
Includes unit tests.
Fixes #111
> Bug fix: false negative unused var

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
Not sure why phpstan is complaining about this now, but it seems to hink
that T_OPEN_SHORT_ARRAY, etc, are strings rather than integers. Doing
this makes it quiet down.
This should have no real effect.
> Always use array for first arg of findPrevious/Next

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithInlineAssignFixture.php
> Helper::getNextAssignPointer(): fix comment tolerance

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithForeachFixture.php
> Helper::findParenthesisOwner(): fix comment tolerance

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithReferenceFixture.php
> Helper::findPreviousFunctionPtr(): fix comment tolerance

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithReferenceFixture.php
> Helper::findFunctionCall[Arguments](): fix comment tolerance

- VariableAnalysis/Lib/Helpers.php
Using `isset()` is significantly faster than a call to `in_array()` and as the PHPCS native `Tokens` class already contains a property representing the tokens being checked for here, we may as well use it.
> Helper::findVariableScope(): performance tweak

- .gitignore
- composer.circleci.json
- composer.json
I've tested and the unit tests as-is are compatible with PHPUnit 7.x and 8.x without needing any adjustments, so we may as well allow using/installing those versions.
Includes widening the version requirements for the `limedeck/phpunit-detailed-printer` to prevent it from being a blocker for using more recent PHPUnit versions.
Version 4.x of the `limedeck/phpunit-detailed-printer` is compatible with PHPUnit 7.x, version 5.x is compatible with PHPUnit 8.x.
Ref: https://github.com/LimeDeck/phpunit-detailed-printer/releases
> Allow running the unit tests on more recent PHPUnit versions

- composer.circleci.json
Follow up on #106 which did this for the "normal" `composer.json` file.
> CircleCI Composer: move PHPCS dependency to `require`

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/GetDefinedVarsFixture.php
> VariableAnalysisSniff::isGetDefinedVars(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithReferenceFixture.php
> VariableAnalysisSniff::checkForFunctionPrototype(): fix comment tolerance in pass by reference declaration

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithTryCatchFixture.php
> VariableAnalysisSniff::checkForCatchBlock(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ClassWithMembersFixture.php
> VariableAnalysisSniff::checkForStaticMember(): fix comment tolerance [1]

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithVariableCallFixture.php
> VariableAnalysisSniff::checkForStaticMember(): fix comment tolerance [2]

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithUseReferenceFixture.php
> VariableAnalysisSniff::checkForFunctionPrototype(): fix comment tolerance in closure use by reference

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithClosureFixture.php
> VariableAnalysisSniff::checkForStaticOutsideClass(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/VariableVariablesFixture.php
> VariableAnalysisSniff::checkForVariableVariable(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/DestructuringFixture.php
> VariableAnalysisSniff::checkForListAssignment(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithGlobalVarFixture.php
> VariableAnalysisSniff::checkForGlobalDeclaration(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/ClassReferenceFixture.php
> VariableAnalysisSniff::checkForSymbolicObjectProperty(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/CompactFixture.php
> VariableAnalysisSniff::processCompactArguments(): fix comment tolerance

- VariableAnalysis/Lib/Helpers.php
Can't find any use of this method anywhere in the code base anymore, so it may as well be removed.
> Helper::areAnyConditionsAClosure(): remove unused method

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/AssignmentByReferenceFixture.php
> VariableAnalysisSniff::checkForAssignment(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/FunctionWithReferenceFixture.php
> VariableAnalysisSniff::checkForPassByReferenceFunctionCall(): fix comment tolerance

- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
- VariableAnalysis/Tests/CodeAnalysis/fixtures/DestructuringFixture.php
- composer.circleci.json
- composer.json
Props to @dlh01 in https://github.com/Automattic/VIP-Coding-Standards/issues/458 who noticed the bug in a different sniff but it's totally applicable here too.
Fixes #130
> Handle nested destructuring assignment

- README.md
The standalone install instructions recommended cloning the repository, but this is not a good idea if you want a stable release. This changes the instructions to suggest downloading the latest release instead.
> Change standalone install instructions to use latest release

- VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php
Closes #162
Note: alternatively the choice could be made to move the `Tests` directory out of the `VariableAnalysis` directory as, as this standard doesn't use the PHPCS native test framework, there is no need for the tests to be in the same directory as the application files.
> Tests: fix namespace

- Tests/VariableAnalysisSniff/VariableAnalysisTest.php
- Tests/VariableAnalysisSniff/fixtures/FunctionWithGlobalVarFixture.php
- Tests/VariableAnalysisSniff/fixtures/UnusedAfterUsedFixture.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
The logic in `areFollowingArgumentsUsed` is flawed; it was not limited to just function arguments, so it was also applying to global variables and scoped variables.
Fixes #170
> Fix unused-before-used detection

- README.md
- VariableAnalysis/ruleset.xml
As part of an effort to make sure that the dependencies are correctly installed, this adds `PHPCSUtils` as a dependency to the sniff. Without this change, it's possible to use `VariableAnalysis` functionally without phpcsutils until we hit a code path that needs it. In the interest of "fail fast" and giving a slightly more helpful error, this will fail immediately if the library is not there.
```
ERROR: Referenced sniff "PHPCSUtils" does not exist
Run "phpcs --help" for usage information
```
This also updates the README to include installation instructions for PHPCSUtils.
> Throw an error if phpcsutils is not available

- .circleci/config.yml
We won't be able to merge this until we have support for PHP 7.4 (#165 ) but this will provide a way of testing those features.
> Add php 7.4 to circleci config

- Tests/VariableAnalysisSniff/VariableAnalysisTest.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
Hi this property is useful for me as in my company they follow a name standard for declaring global variables (I don't like that, but it's annoying to constantly pollute the undeclared warnings with those). Just in case you'd like to include this in the master branch. Thanks for this great project BTW.
> Added property validUndefinedVariableRegexp to VariableAnalysisSniff

- composer.json
The Dealerdirect Composer PHPCS plugin is already a (non-dev) requirement of PHPCSUtils, so will be installed whether you require it or not.
By removing it from the `composer.json` file, potential conflicts between the versions allowed by PHPCSUtils and this plugin are prevented.
Note: The plugin has released a new version last week and the new version of PHPCSUtils which was also released a few days back, already allows for it. The new version of the plugin includes support for Composer 2.0 and allows for testing standards with the plugin on PHP 8 and with PHPCS 4.x-dev.
Ref: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.7.0
> Composer: remove the Composer PHPCS plugin

- README.md
- Tests/VariableAnalysisSniff/ArrowFunctionTest.php
- Tests/VariableAnalysisSniff/VariableArgumentListTest.php
- Tests/VariableAnalysisSniff/fixtures/ArrowFunctionFixture.php
- Tests/VariableAnalysisSniff/fixtures/VariableArgumentListFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Lib/ScopeInfo.php
- VariableAnalysis/Lib/ScopeType.php
- VariableAnalysis/Lib/VariableInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- composer.json
> Add arrow function support

- Tests/VariableAnalysisSniff/VariableAnalysisTest.php
- Tests/VariableAnalysisSniff/fixtures/AssignmentByReferenceFixture.php
- Tests/VariableAnalysisSniff/fixtures/FunctionWithUseReferenceFixture.php
- Tests/VariableAnalysisSniff/fixtures/UnusedVarWithValueChangeFixture.php
- VariableAnalysis/Lib/VariableInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This removes the multiple different ways used to track variable references and instead uses one.
This follows on the work done in #126/#128 and #120 and fixes some edge cases there. Notably, the sniff now treats a local assignment by reference (eg: `$foo = &$bar;`) as a declaration, not an initialization, since it doesn't really modify the value of anything, it effectively just creates an alias. That means that if the alias is unused, it should be reported as unused (which was already sort-of happening but it was a bit of a hack). 
It also means that before we make such an alias, we should check and report if the variable is unused from a previous binding or assignment because after that point, it will effectively be a new variable.
The biggest change in this PR is probably that now every …
> Refactor and clean up reference variables

- Tests/VariableAnalysisSniff/IfConditionTest.php
- Tests/VariableAnalysisSniff/fixtures/FunctionWithIfConditionFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
> Add special cases for variables used in `else` blocks

- Tests/VariableAnalysisSniff/GlobalScopeTest.php
- Tests/VariableAnalysisSniff/VariableAnalysisTest.php
- Tests/VariableAnalysisSniff/fixtures/AnonymousClassWithPropertiesFixture.php
- Tests/VariableAnalysisSniff/fixtures/FunctionWithGlobalVarFixture.php
- Tests/VariableAnalysisSniff/fixtures/GlobalScopeFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This PR adds the long-overdue support for finding unused variables in the global (really, the file) scope.
Fixes #37
> Support global scope

- .circleci/config.yml
- README.md
- Tests/BaseTestCase.php
- VariableAnalysis/Lib/Helpers.php
- composer.circleci.json
- composer.json
There was never a good reason to disallow running under PHP 5.4. This downgrades the requirement and adds CI tests.
> Downgrade requirements from PHP 5.6 to 5.4

- README.md
- Tests/VariableAnalysisSniff/GlobalScopeTest.php
- Tests/VariableAnalysisSniff/fixtures/GlobalScopeFixture.php
- VariableAnalysis/Lib/ScopeInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This adds a new option called `allowUndefinedVariablesInFileScope` that, if set, will never set a variable defined at the file's top-level scope to undefined.
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/125
> Add allowUndefinedVariablesInFileScope option

- VariableAnalysis/ruleset.xml
- VariableAnalysis/ruleset.xml.example
This removes most of the details from ruleset.xml.example and refers to the README for details since the README is much more likely to remain up-to-date than the xml file.
Fixes #118
> Fix example ruleset

- README.md
- Tests/VariableAnalysisSniff/UnusedFollowedByRequireTest.php
- Tests/VariableAnalysisSniff/fixtures/UnusedFollowedByRequireFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This adds a new option, `allowUnusedVariablesBeforeRequire`. If set to `true`, variables defined before a `require`, `require_once`, `include`, or `include_once` will not be marked as unused. They may be intended for the required file.
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/105
> Add allowUnusedVariablesBeforeRequire option

- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Lib/ScopeInfo.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This PR tackles the largest performance issues with the sniff that I was able to find:
- We were searching to see if every single token processed was a scope closer. Now we cache that data when we find it instead.
- When testing to see if every variable is inside an arrow function, we were using `FunctionDeclarations::isArrowFunction` on every token before it in the scope. Now we only check tokens that have a content of `'fn'`.
In my testing with a large file, this reduced the runtime from about 2 minutes to about 2 seconds.
> Fix performance issues around scope close detection

- Tests/VariableAnalysisSniff/IssetTest.php
- Tests/VariableAnalysisSniff/fixtures/IssetFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
PHP allows undefined variables to be used inside `isset()` and `empty()`. This change prevents such usages from generating warnings.
Note that this only affects the usage of variables inside the call sites of those functions, it does not mean that a variable who's existence is confirmed with `isset()` will not be marked as undefined in later reads. That's definitely not ideal, but detecting those use-cases is very difficult, as described in [this comment](https://github.com/sirbrillig/phpcs-variable-analysis/issues/202#issuecomment-688507314).
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/202
> Allow undefined variables inside `isset` and `empty`

- README.md
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This (breaking!) change replaces `UnusedVariable` warnings for function arguments with `UnusedParameter` and `UnusedParameterBeforeUsed`.
The options `allowUnusedParametersBeforeUsed` and `allowUnusedFunctionParameters` continue to work as before including that `allowUnusedParametersBeforeUsed` defaults to true, meaning that `UnusedParameterBeforeUsed` will never show normally unless that option is explicitly set to false.
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/175
> Replace UnusedVariable with UnusedParameter for parameters

- README.md
- Tests/VariableAnalysisSniff/ArrayAssignmentShortcutTest.php
- Tests/VariableAnalysisSniff/fixtures/ArrayAssignmentShortcutFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This replaces the `UndefinedVariable` sniff code with `UndefinedArrayVariable` if the variable is an "array push shortcut" (I don't know of a better name for it): `$x[] = 5;`
Also, when marking such a variable, this sniff considers that variable defined at that point going forward. (This will prevent future uses of the same variable from being reported as undefined.)
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/98
> Add sniff codes for array assignment shortcut

- Tests/VariableAnalysisSniff/fixtures/FunctionWithGlobalVarFixture.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This adds support for [some superglobals](https://www.php.net/manual/en/reserved.variables.php) which were previously missing: 
- `$http_response_header`
- `$HTTP_RAW_POST_DATA`
- `$php_errormsg`
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/176
> Add missing superglobals

- README.md
- Tests/VariableAnalysisSniff/UnsetTest.php
- Tests/VariableAnalysisSniff/fixtures/UnsetFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
This replaces the `UndefinedVariable` sniff code with a new `UndefinedUnsetVariable` code for undefined variables that are used within the `unset()` function. Technically this is legal PHP, but it may be a sign of a typo. This sniff code allows refined control of such warnings.
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/174
> Add UndefinedUnsetVariable sniff code

- Tests/VariableAnalysisSniff/IfConditionTest.php
- Tests/VariableAnalysisSniff/fixtures/FunctionWithIfConditionFixture.php
- Tests/VariableAnalysisSniff/fixtures/FunctionWithInlineIfConditionFixture.php
#205 made it so that future uses of a variable after an array push are marked as defined. However, that is incorrect in the case of the array assignment being within the body of an `if` statement, an `else` statement, or a `while`, `do`, or `for` loop.
This modifies the code such that those cases are correctly reported as undefined variables.
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/210
> Add tests for if/loop condition undefined array

- Tests/VariableAnalysisSniff/WhileLoopTest.php
- Tests/VariableAnalysisSniff/fixtures/FunctionWithWhileLoopFixture.php
- VariableAnalysis/Lib/Constants.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
Concatenation (or other variable assignment) counts as a "write" to a variable, but not as a "read". That way code like this produces an unused variable warning:
```php
$foo = 'hi';
$foo .= ' friend';
```
However, in PHP if the assignment is _inside_ another expression, then the assignment should count as a "read" as well, as in the following code, which should produce no warning:
```
$foo = 'hi';
sayHi($foo .= ' friend');
```
This PR makes the sniff aware of two such cases: when the assignment is on the right-hand-side (RHS) of another assignment, or when the assignment is inside a function call. There may be other expressions that an assignment could be part of, but this should take care of the majority of them.
Fixes #183
> Mark concatenation inside another expression as variable read

- README.md
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
- VariableAnalysis/ruleset.xml
- composer.circleci.json
- composer.json
Although PHPCSUtils presents an amazing mechanism for this package to improve its compatibility and reduce false positives, as a project it remains in an alpha state and in the meantime it blocks this package from all the features added since the 2.x branch. Notably, PHP 7.4 support and improved scope detection.
This PR backports the entirety of the 3.0 branch to 2.x with the PHPCSUtils imports replaced with custom local versions that, while certainly less effective and complete than the PHPCSUtils versions, at least make the tests pass.
This would allow us to release version 2.10.0 with a lot of improvements and keep 3.0 waiting on the PHPCSUtils release cycle (which itself is waiting on PHPCS).
> Backport all of 3.0 to 2.x without phpcsutils

- Tests/VariableAnalysisSniff/fixtures/FunctionWithReferenceFixture.php
- VariableAnalysis/Lib/Helpers.php
- VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
When marking a variable as used, we also check to see if that variable is a reference to another variable, and if so we mark the referenced variable as used also. However, it's possible to have a reference variable that doesn't reference anything until runtime.
Because `markVariableAssignment` will create a variable record if one does not exist, this caused non-existent variable records to be created for unbound reference variables. These references (since they didn't refer to a real variable) were always unused. This caused false positive warnings about unused variables.
This PR fixes the problem by making sure that the referenced variable exists before calling `markVariableAssignment`.
Fixes https://github.com/sirbrillig/phpcs-variable-analysis/issues/215
> Fix array_walk pass-by-reference in 2.x
